---
namespace: hornjo
name: sonicos
version: null
readme: README.md
authors:
  - Johannes Horn (@hornjo)
  - Marco Fuchs (@FuxMak)
description: Manages the sonicos with features provided by the API.
license:
  - GPL-2.0-or-later
tags:
  - sonicwall
  - firewall
  - networking

dependencies: {}
repository: https://github.com/hornjo/sonicos
documentation: https://github.com/hornjo/sonicos/blob/main/README.md
homepage: https://hornjo.github.io
issues: https://github.com/hornjo/sonicos/issues
