POST https://172.27.72.39/api/sonicos/auth
Accept: {application/json}

Content-type: application/json

{

  "username":"admin",

  "password":"Letmein123!",


}

GET https://172.27.72.39/api/sonicos/address-groups/ipv4 HTTP/1.1
